//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renocan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Renocan_DbContext : DbContext
    {
        public Renocan_DbContext()
            : base("name=Renocan_DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Admin_Signup> Admin_Signup { get; set; }
        public virtual DbSet<Bookmark> Bookmarks { get; set; }
        public virtual DbSet<Client_Signup> Client_Signup { get; set; }
        public virtual DbSet<Company_Service_Location> Company_Service_Location { get; set; }
        public virtual DbSet<Image_Gallary> Image_Gallary { get; set; }
        public virtual DbSet<Image_Type> Image_Type { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Registration_Company> Registration_Company { get; set; }
        public virtual DbSet<Request_Review_History> Request_Review_History { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Scoreboard> Scoreboards { get; set; }
        public virtual DbSet<Service_Category> Service_Category { get; set; }
        public virtual DbSet<Service_Request> Service_Request { get; set; }
        public virtual DbSet<Service_Request_Status> Service_Request_Status { get; set; }
        public virtual DbSet<Service_Review_Status> Service_Review_Status { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<VIisitor_Log> VIisitor_Log { get; set; }
    }
}
