//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renocan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Review_ID { get; set; }
        public Nullable<int> Service_Request_ID { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<int> Service_Review_Status_ID { get; set; }
        public string Review_Title { get; set; }
        public string Approximate_Cost { get; set; }
        public string Review_Details { get; set; }
        public Nullable<int> Review_Rating { get; set; }
        public Nullable<System.TimeSpan> Review_Time { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public string Creation_By { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public byte[] Ip { get; set; }
    }
}
